# Setup
title:               Tommy bloggt
tagline:             'Some things that matter to me'
description:         'My personal developer blog around PHP and other programming stuff.'
url:                 //tommy-muehle.github.io
baseurl:             ''
paginate:            1
permalink:           pretty

twitter:
  username:         "tommy_muehle"
social:
  links:
    - https://github.com/tommy-muehle
    - https://www.xing.com/profile/Tommy_Muehle

# Custom vars
version:             2.0.0

gems:
 - jekyll-paginate
 - jekyll-seo-tag
 - jekyll-twitter-plugin

markdown:            kramdown
